\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<>>=
#trabajando con funciones
#function(){}#en () va lo que vamos a ingresar se un objeto, 2,3 en {}lo que hace la función

suma<-function(x,y){
  adicion <- x+y
  resta<-x-y
print(adicion) #imprimir adicion
print (resta) #imprimir resta
}

suma(2,5) # hace las operaciones con esos numeros x=2 & y=5
suma(5,2) 
@



\end{document}
